### ISSUE TITLE
Thank you a lot vvvvvery much!

### ISSUE THREAD

**Issue by Amfacter** [demonlord1997/PlotNeuralNet#1]
n_filer不居中给我整麻了，我搜索demonlord1997也没有搜到，太感谢了，谢谢大佬！

**Comment by Kurama622** [comment]
我github改名了，demonlord太中二了

**Comment by Amfacter** [comment]
我的哥，请你赶紧在CSDN上发一篇帖子，特地说明你能把n_filer居中显示，我看见有很多人都在查找这个问题，把博主都问懵了，还有，刚刚运行了一下你的文件，好像tikzmake.sh里面的路径是基于Linux的，我把/usr/local/texlive/2019/bin/x86_64-linux/xelatex $1.tex 换成了 pdflatex $1.tex 后就好了，现在运行出来就是居中显示了，今天花了大半天，终于在这篇文章李找到线索，https://tcsds.github.io/2021/05/10/%E9%9D%A2%E5%90%91Python%E7%9A%84PlotNeuralNet%E6%95%99%E7%A8%8B/，然后我就取搜索demonlord1997，github再怎么搜索也搜不到，我直接炸裂，然后就去github上看，发现你这个就是我想要的，赶紧写个感谢！还好最终解决了，很多人都不会用github，我也不怎么会，主要是英语不太行



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StubbornVegeta/PlotNeuralNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月26日(星期二) 晚上9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StubbornVegeta/PlotNeuralNet] Thank you a lot vvvvvery much! (Issue #1)



 
我github改名了，demonlord太中二了

**Comment by Kurama622** [comment]
我看到你在那个blog下面的评论了，你已经说明了我就不再发帖子了，感谢
